# Generated by Django 4.1.5 on 2023-01-22 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='countInStoc',
            new_name='countInStock',
        ),
    ]
